apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "authz"
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin 
  rules:
  - from:
    - source:
        namespaces: ["default"]
        #principals: ["cluster.local/ns/default/sa/bookinfo-productpage"]
    to:
    - operation:
        methods: ["GET"]
