apiVersion: v1
kind: Service
metadata:
  name: my-nginx-2
  labels:
    run: my-nginx-2
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https-nginx
  selector:
    run: my-nginx-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-2
spec:
  selector:
    matchLabels:
      run: my-nginx-2
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx-2
    spec:
      containers:
      - name: my-nginx-2
        image: gcr.io/jianfeih-test/nginx-curl:20200430
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
          readOnly: true
        - name: nginx-server-certs
          mountPath: /etc/nginx-server-certs
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap
      - name: nginx-server-certs
        secret:
          secretName: nginx-server-certs